name: Build, Test, and Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Restore Test Dependencies
      run: dotnet restore ./ProductApi/ProductApi.csproj

    - name: Run Resilience Tests
      run: dotnet test --no-build --filter FullyQualifiedName~ProductApi.ResilienceTests --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'threeamigosapi' 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE1 }}
        package: ./publish
